server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    platform: postgres
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/registration
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
    show-sql: true